#!/bin/sh
# 获取CPU温度
cpu_temp=$(cat /sys/devices/virtual/thermal/thermal_zone0/hwmon0/temp1_input 2>/dev/null | awk '{printf("%.1f°C", $0 / 1000)}')

# 输出结果
if [ -n "$cpu_temp" ]; then
    echo -n "CPU: $cpu_temp"
else
    echo -n "No temperature info"
fi
